### PANDAS

In [1]:
import pandas as pd

print(pd.__version__)

3.0.6

### SERIES Y DATAFRAME

In [ ]:
# una serie es un arran 1D
serie = pd.Series(
    [10, 20, 30],
    index = ['a', 'b', 'c'],
    name = 'ventas'    
)

serie

a    10
b    20
c    30
Name: ventas, dtype: int64

In [5]:
# un DataFrame es un array 2D
df = pd.DataFrame({
    "producto": ['A', 'B'],
    'unidades': [10, 20]
    }
)

df

  producto  unidades
0        A        10
1        B        20

### CREACIÓN DE UNA SERIE

In [8]:
serie_ventas = pd.Series(
    [120, 85, 200, 45],
    index = ['enero', 'febrero', 'marzo', 'abril'],
    name = 'ventas'
)

serie_ventas
serie_ventas.min()

np.int64(45)

### DATAFRAME
DESDE UN DICCIONARIO

In [9]:
df = pd.DataFrame({
    'producto': ['laptop', 'monitor', 'teclado'],
    'unidades': [3, 7, 12],
    'precio': [1200, 320, 95]    
})

print(df)

  producto  unidades  precio
0   laptop         3    1200
1  monitor         7     320
2  teclado        12      95

LISTA DE DICCIONARIO

In [10]:
df2 = pd.DataFrame(
    [
        {'producto': 'laptop', 'unidades': 3, 'precio': 1200},
        {'producto': 'monitor', 'unidades': 7, 'precio': 320}
    ]
)

df2

  producto  unidades  precio
0   laptop         3    1200
1  monitor         7     320

DESDE UNA LISTA DE LISTA

In [11]:
df3 = pd.DataFrame(
    [
        ['laptop', 3, 1200],
        ['monitor', 7, 350]
    ],
    columns=['producto', 'unidiades', 'precio']
)
df3

  producto  unidiades  precio
0   laptop          3    1200
1  monitor          7     350

### COLUMNAS CALCULADAS

In [12]:
df = pd.DataFrame({
    'producto': ['laptop', 'monitor', 'teclado'],
    'unidades': [3, 7, 12],
    'precio': [1200, 320, 95]    
})

df['importe'] = df['unidades']*df['precio']

df

  producto  unidades  precio  importe
0   laptop         3    1200     3600
1  monitor         7     320     2240
2  teclado        12      95     1140

In [16]:
# un DataFrame es un conjunto de Series
df['unidades'].min()

np.int64(3)

In [ ]:
# shape devuelve las dimensiones del dataframe (filas , columnas)
df.shape

(3, 4)

In [15]:
# columns devuelve el nombre de las columnas
df.columns
df.columns.to_list() # transforma las columnas en lista

['producto', 'unidades', 'precio', 'importe']