### INDEXACIÓN

In [3]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [4]:
ventas_df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [ ]:
# traer algunas columnas del DataFrame -> pasale la lista de campos
ventas_df[["vendedor", "producto", "categoria"]]

         vendedor     producto   categoria
0      Pedro Diaz  Auriculares  Accesorios
1      Luis Gomez   Monitor 27  Tecnologia
2     Carlos Vega   Silla Ergo  Mobiliario
3      Pedro Diaz   Laptop Pro  Tecnologia
4      Elena Mora  Auriculares  Accesorios
...           ...          ...         ...
1195   Luis Gomez   Raton Ergo  Accesorios
1196   Marta Ruiz   Laptop Pro  Tecnologia
1197   Ana Torres   Monitor 27  Tecnologia
1198   Ana Torres   Monitor 27  Tecnologia
1199   Marta Ruiz   Raton Ergo  Accesorios

[1200 rows x 3 columns]

### LOC

In [ ]:
# indexar ILOC[Filas, Columnas] 
# localia las filas por indice, dado que las columnas no tienen indice se debe usar su etiqueta o nombre

ventas_df.loc[0:4] #trae las filas del index 0 al 4

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [7]:
ventas_df.loc[0:4, ['vendedor', 'producto', 'categoria']]

      vendedor     producto   categoria
0   Pedro Diaz  Auriculares  Accesorios
1   Luis Gomez   Monitor 27  Tecnologia
2  Carlos Vega   Silla Ergo  Mobiliario
3   Pedro Diaz   Laptop Pro  Tecnologia
4   Elena Mora  Auriculares  Accesorios

In [8]:
# desde el indice 1000 hacia adelante
ventas_df.loc[1000:, ['vendedor', 'producto', 'categoria']]

        vendedor     producto   categoria
1000  Luis Gomez  Teclado Mec  Accesorios
1001  Luis Gomez  Teclado Mec  Accesorios
1002  Sofia Leon   Monitor 27  Tecnologia
1003  Luis Gomez   Raton Ergo  Accesorios
1004  Luis Gomez   Laptop Pro  Tecnologia
...          ...          ...         ...
1195  Luis Gomez   Raton Ergo  Accesorios
1196  Marta Ruiz   Laptop Pro  Tecnologia
1197  Ana Torres   Monitor 27  Tecnologia
1198  Ana Torres   Monitor 27  Tecnologia
1199  Marta Ruiz   Raton Ergo  Accesorios

[200 rows x 3 columns]

In [9]:
# las primeras 1000
ventas_df.loc[1000:, ['vendedor', 'producto', 'categoria']]

        vendedor     producto   categoria
1000  Luis Gomez  Teclado Mec  Accesorios
1001  Luis Gomez  Teclado Mec  Accesorios
1002  Sofia Leon   Monitor 27  Tecnologia
1003  Luis Gomez   Raton Ergo  Accesorios
1004  Luis Gomez   Laptop Pro  Tecnologia
...          ...          ...         ...
1195  Luis Gomez   Raton Ergo  Accesorios
1196  Marta Ruiz   Laptop Pro  Tecnologia
1197  Ana Torres   Monitor 27  Tecnologia
1198  Ana Torres   Monitor 27  Tecnologia
1199  Marta Ruiz   Raton Ergo  Accesorios

[200 rows x 3 columns]