### INDEXACIÓN

In [3]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [4]:
ventas_df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [ ]:
# traer algunas columnas del DataFrame -> pasale la lista de campos
ventas_df[["vendedor", "producto", "categoria"]]

         vendedor     producto   categoria
0      Pedro Diaz  Auriculares  Accesorios
1      Luis Gomez   Monitor 27  Tecnologia
2     Carlos Vega   Silla Ergo  Mobiliario
3      Pedro Diaz   Laptop Pro  Tecnologia
4      Elena Mora  Auriculares  Accesorios
...           ...          ...         ...
1195   Luis Gomez   Raton Ergo  Accesorios
1196   Marta Ruiz   Laptop Pro  Tecnologia
1197   Ana Torres   Monitor 27  Tecnologia
1198   Ana Torres   Monitor 27  Tecnologia
1199   Marta Ruiz   Raton Ergo  Accesorios

[1200 rows x 3 columns]

### LOC

In [ ]:
# indexar ILOC[Filas, Columnas] 
# localia las filas por indice, dado que las columnas no tienen indice se debe usar su etiqueta o nombre

ventas_df.loc[0:4] #trae las filas del index 0 al 4

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [7]:
ventas_df.loc[0:4, ['vendedor', 'producto', 'categoria']]

      vendedor     producto   categoria
0   Pedro Diaz  Auriculares  Accesorios
1   Luis Gomez   Monitor 27  Tecnologia
2  Carlos Vega   Silla Ergo  Mobiliario
3   Pedro Diaz   Laptop Pro  Tecnologia
4   Elena Mora  Auriculares  Accesorios

In [8]:
# desde el indice 1000 hacia adelante
ventas_df.loc[1000:, ['vendedor', 'producto', 'categoria']]

        vendedor     producto   categoria
1000  Luis Gomez  Teclado Mec  Accesorios
1001  Luis Gomez  Teclado Mec  Accesorios
1002  Sofia Leon   Monitor 27  Tecnologia
1003  Luis Gomez   Raton Ergo  Accesorios
1004  Luis Gomez   Laptop Pro  Tecnologia
...          ...          ...         ...
1195  Luis Gomez   Raton Ergo  Accesorios
1196  Marta Ruiz   Laptop Pro  Tecnologia
1197  Ana Torres   Monitor 27  Tecnologia
1198  Ana Torres   Monitor 27  Tecnologia
1199  Marta Ruiz   Raton Ergo  Accesorios

[200 rows x 3 columns]

In [9]:
# las primeras 1000
ventas_df.loc[1000:, ['vendedor', 'producto', 'categoria']]

        vendedor     producto   categoria
1000  Luis Gomez  Teclado Mec  Accesorios
1001  Luis Gomez  Teclado Mec  Accesorios
1002  Sofia Leon   Monitor 27  Tecnologia
1003  Luis Gomez   Raton Ergo  Accesorios
1004  Luis Gomez   Laptop Pro  Tecnologia
...          ...          ...         ...
1195  Luis Gomez   Raton Ergo  Accesorios
1196  Marta Ruiz   Laptop Pro  Tecnologia
1197  Ana Torres   Monitor 27  Tecnologia
1198  Ana Torres   Monitor 27  Tecnologia
1199  Marta Ruiz   Raton Ergo  Accesorios

[200 rows x 3 columns]

ILOC

In [ ]:
# a diferencia del loc, te trae en función al integer ejemplo iloc[0:4], te trae 0 al 3, cuatro elementos al igual que las listas osea por posición

ventas_df.iloc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0

In [12]:
ventas_df.iloc[0:4, 0:2]

        fecha  region
0  2024-01-02   Oeste
1  2024-01-02     Sur
2  2024-01-02  Centro
3  2024-01-02  Centro

### Sorting de columnas

In [13]:
ventas_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [16]:
ventas_df["unidades"].min()

ventas_df["unidades"].max()

np.int64(14)

In [14]:
ventas_df.sort_values(by="unidades", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
54,2024-01-17,Norte,Luis Gomez,Silla Ergo,Mobiliario,1,280,0.00
491,2024-06-07,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,0.15
...,...,...,...,...,...,...,...,...
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.00
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.10
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.00
828,2024-09-12,Centro,Ana Torres,Raton Ergo,Accesorios,14,45,0.05
841,2024-09-16,Sur,Carlos Vega,Teclado Mec,Accesorios,14,95,0.00

In [18]:
ventas_df.sort_values(by="precio_unitario", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
301,2024-04-03,Norte,Carlos Vega,Laptop Pro,Tecnologia,2,1200,0.00
875,2024-09-26,Centro,Javier Sanz,Laptop Pro,Tecnologia,8,1200,0.10
871,2024-09-25,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.05
868,2024-09-24,Norte,Elena Mora,Laptop Pro,Tecnologia,6,1200,0.00
310,2024-04-08,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200,NaN
...,...,...,...,...,...,...,...,...
1187,2024-12-28,Este,Ana Torres,Raton Ergo,Accesorios,8,45,0.05
274,2024-03-27,Norte,Javier Sanz,Raton Ergo,Accesorios,2,45,0.00
1193,2024-12-30,Centro,Ana Torres,Raton Ergo,Accesorios,7,45,0.00
425,2024-05-15,Sur,Ana Torres,Raton Ergo,Accesorios,10,45,0.10
428,2024-05-15,Centro,Ana Torres,Raton Ergo,Accesorios,9,45,0.00

In [20]:
ventas_df.sort_values(by=["region", "unidades"], ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
70,2024-01-24,Centro,Luis Gomez,Auriculares,Accesorios,1,130,0.10
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320,NaN
...,...,...,...,...,...,...,...,...
1080,2024-11-26,Sur,Javier Sanz,Escritorio,Mobiliario,14,450,0.10
1081,2024-11-26,Sur,Marta Ruiz,Monitor 27,Tecnologia,14,320,0.05
1086,2024-11-28,Sur,Sofia Leon,Laptop Pro,Tecnologia,14,1200,0.15
1130,2024-12-09,Sur,Pedro Diaz,Teclado Mec,Accesorios,14,95,0.15
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00

In [21]:
ventas_df.sort_values(by=["region", "unidades"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00