### FILTROS

In [1]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv")
ventas_df.head(20)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.00
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.00
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320,0.10
11,2024-01-04,Oeste,Pedro Diaz,Escritorio,Mobiliario,10,450,0.05
12,2024-01-04,Centro,Marta Ruiz,Tablet Air,Tecnologia,2,640,0.15
13,2024-01-05,Norte,Sofia Leon,Auriculares,Accesorios,11,130,0.00
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
15,2024-01-06,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,8,1200,0.00
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130,0.10
19,2024-01-06,Norte,Sofia Leon,Monitor 27,Tecnologia,8,320,0.05

In [ ]:
# mascara
ventas_df["region"] == 'Sur'

0       False
1        True
2       False
3       False
4        True
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: region, Length: 1200, dtype: bool

In [3]:
#
ventas_df[ventas_df["region"]=="Sur"]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [5]:
#
filtro = ventas_df["region"]=="Sur"
ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [ ]:
# subset= , le decimos de un determinado campo
ventas_df[ventas_df["region"]=="Sur"].value_counts(subset="region")

region
Sur    240
Name: count, dtype: int64

In [ ]:
# operador Y -> &            
# operador O -> |
filtro = (ventas_df['region']== "Sur") & (ventas_df["precio_unitario"]>90)
ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [9]:
ventas_df[filtro]["precio_unitario"].min()

np.int64(95)

In [10]:
ventas_df[filtro]["region"].unique()

<StringArray>
['Sur']
Length: 1, dtype: str

In [13]:
filtro = (ventas_df['region']=='Sur') | (ventas_df['region']=='Norte')

ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.0

In [14]:
ventas_df[filtro]['region'].unique()

<StringArray>
['Sur', 'Norte']
Length: 2, dtype: str

In [15]:
filtro = ventas_df['descuento'] == 0.1
ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320,0.1
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130,0.1
20,2024-01-07,Centro,Sofia Leon,Auriculares,Accesorios,5,130,0.1
...,...,...,...,...,...,...,...,...
1135,2024-12-12,Este,Carlos Vega,Escritorio,Mobiliario,9,450,0.1
1165,2024-12-20,Centro,Marta Ruiz,Silla Ergo,Mobiliario,2,280,0.1
1166,2024-12-20,Norte,Luis Gomez,Auriculares,Accesorios,11,130,0.1
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200,0.1
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.1

In [16]:
ventas_df[filtro]['descuento'].unique()

array([0.1])

In [18]:
filtro = ventas_df['region']!= 'Sur'

ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.00
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.00
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [19]:
ventas_df[filtro]['region'].unique()

<StringArray>
['Oeste', 'Centro', 'Norte', 'Este']
Length: 4, dtype: str

In [21]:
# filtro = (ventas_df['region']=='Sur') | (ventas_df['region']=='Norte')
filtro = ventas_df['region'].isin(['Sur', 'Norte'])

ventas_df[filtro]['region'].unique()

<StringArray>
['Sur', 'Norte']
Length: 2, dtype: str

In [27]:
filtro = (ventas_df['precio_unitario'] >= 90) & (ventas_df['precio_unitario'] <= 200)
ventas_df[filtro]['precio_unitario'].value_counts()

precio_unitario
130    158
95     133
Name: count, dtype: int64

In [28]:
# equivalente filtro = (ventas_df['precio_unitario'] >= 90) & (ventas_df['precio_unitario'] <= 200)
# cuando el operador es mayor o igual - menor o igual
filtro = ventas_df['precio_unitario'].between(90, 200)
ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
13,2024-01-05,Norte,Sofia Leon,Auriculares,Accesorios,11,130,0.00
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1173,2024-12-22,Norte,Marta Ruiz,Teclado Mec,Accesorios,12,95,0.05
1177,2024-12-24,Oeste,Ana Torres,Auriculares,Accesorios,11,130,0.00
1183,2024-12-26,Centro,Luis Gomez,Auriculares,Accesorios,6,130,0.00
1189,2024-12-29,Oeste,Javier Sanz,Auriculares,Accesorios,6,130,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [30]:
ventas_df[filtro]["precio_unitario"].value_counts()

precio_unitario
130    158
95     133
Name: count, dtype: int64

In [32]:
# filtro
filtro = (ventas_df['categoria'] == "Tecnologia") & (ventas_df['unidades'] > 10)
ventas_df[filtro]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
27,2024-01-09,Este,Carlos Vega,Laptop Pro,Tecnologia,12,1200,0.00
40,2024-01-14,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200,0.10
89,2024-01-31,Centro,Sofia Leon,Monitor 27,Tecnologia,12,320,0.00
...,...,...,...,...,...,...,...,...
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200,0.00
1176,2024-12-23,Centro,Carlos Vega,Monitor 27,Tecnologia,11,320,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1188,2024-12-28,Este,Luis Gomez,Tablet Air,Tecnologia,13,640,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05

In [ ]:
# tener en cuenta que el 2do corteche cuando es mas de un campo se pasa como lista
ventas_df[filtro][['categoria', 'unidades']].value_counts()

categoria   unidades
Tecnologia  12          32
            13          29
            14          27
            11          27
Name: count, dtype: int64