In [1]:
import pandas as pd

df = pd.read_csv('../data/clientes_sucio.csv')

df.head(15)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
4,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
10,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        12 non-null     str
 1   nombre       11 non-null     str
 2   ciudad       12 non-null     str
 3   fecha_nac    12 non-null     str
 4   gasto_total  9 non-null      str
 5   activo       12 non-null     str
 6   telefono     9 non-null      str
dtypes: str(7)
memory usage: 1.5 KB

# ENCONTRAR DUPLICADOS

In [3]:
# una mascara boleana, indica True el registro duplicado osea igual en todos los campos 
filtro = df.duplicated()
filtro

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [4]:
# drop_duplicates -> eliminar duplicados
clientes_sin_duplicados = df.drop_duplicates()
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [5]:
# strip -> elimina espacios al inicial y final
# lower -> pasa a minuscula

clientes_sin_duplicados['email'].str.strip().str.lower()

0       ana.lopez@mail.com
1      luis.perez@mail.com
2         marta.r@mail.com
3      pedro.diaz@mail.com
5      sofia.leon@mail.com
6     carlos.vega@mail.com
7      elena.mora@mail.com
8     javier.sanz@mail.com
9     lucia.ortiz@mail.com
11    miguel.cano@mail.com
Name: email, dtype: str

In [6]:
clientes_sin_duplicados['email'] = clientes_sin_duplicados['email'].str.strip().str.lower()
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [7]:
# title() para nombre y ciudad
clientes_sin_duplicados['nombre'] = clientes_sin_duplicados['nombre'].str.title()
clientes_sin_duplicados['ciudad'] = clientes_sin_duplicados['ciudad'].str.title()
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [8]:
clientes_sin_duplicados['fecha_nac'] = pd.to_datetime(
    clientes_sin_duplicados['fecha_nac'],
    format='mixed'
)

clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [9]:
# darle un trataminto de una columna de texto para convertirla a formato numerico y pode realizar operaciones
# usando map y casteo a float64

def conversor_apunto_flotante(x: str)-> str:
    if x:
        return str(x).replace(".", "").replace(",", ".")
    return x

In [10]:
#clientes_sin_duplicados['gasto_total'].map(
#    lambda x: str(x).replace(".", "").replace(",", ".")
#)

clientes_sin_duplicados['gasto_total'] = clientes_sin_duplicados['gasto_total'].str.replace(".","").str.replace(",", ".").astype(pd.Float64Dtype())
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,si,600654321

In [11]:
# activo
#clientes_sin_duplicados['activo'] = clientes_sin_duplicados['activo'].str.lower().str.replace(
    #{"si":"True", 'no': "False"}
#)
clientes_sin_duplicados['activo'] = clientes_sin_duplicados['activo'].str.lower().str.replace(
    {"si":"1", 'no': "0"}
).astype(int).astype(bool)

clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,True,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,True,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,False,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,False,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,True,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,True,600654321

In [12]:
# quitando los espacios y simbolos
clientes_sin_duplicados['telefono'] = clientes_sin_duplicados['telefono'].str.replace(r"\D","", regex=True)
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,True,34600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,True,600222333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,False,600444555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,False,34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,True,600999000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,True,600654321

In [13]:
clientes_sin_duplicados.to_csv("../data/clientes_limpios.csv", index=False)

In [ ]:
# para guardar en parquet se usa la liberia pyarrow
# uv pyarrow

clientes_sin_duplicados.to_parquet(
    "../data/clientes_limpios.parquet.gzip",
    index=False,
    compression="zstd"
)

In [16]:
cliente_prueba = pd.read_parquet("../data/clientes_limpios.parquet.gzip")
cliente_prueba.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        10 non-null     str
 1   nombre       9 non-null      str
 2   ciudad       10 non-null     str
 3   fecha_nac    10 non-null     datetime64[us]
 4   gasto_total  7 non-null      Float64
 5   activo       10 non-null     bool
 6   telefono     8 non-null      str
dtypes: Float64(1), bool(1), datetime64[us](1), str(4)
memory usage: 1.0 KB