In [1]:
import pandas as pd

ventas_df = pd.read_csv('../data/ventas.csv')

ventas_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [3]:
ventas_df['importe'] = ventas_df['unidades'] * ventas_df['precio_unitario']
ventas_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,650
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,4480
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,280
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,12000
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,260
...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,180
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,15600
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,640
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,1920
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00,360

## REPORTE DE LAS VENTAS TODALES POR REGION

In [5]:
# para una sola region
ventas_df[ventas_df['region'] == 'Sur']['importe'].sum()

np.int64(699920)

In [ ]:
# usamos el groupby(campo a agrupar)
# mas rapido
ventas_df.groupby('region')['importe'].sum()

region
Centro    705695
Este      549745
Norte     862360
Oeste     626295
Sur       699920
Name: importe, dtype: int64

In [6]:
# el promedio por region
ventas_df.groupby('region')['importe'].mean()

region
Centro    2594.466912
Este      3054.138889
Norte     2827.409836
Oeste     3085.197044
Sur       2916.333333
Name: importe, dtype: float64

In [ ]:
# varias estadisticas
# para eso se usa .agg() -> se le puede pasar varias estadisticas como lista
ventas_df.groupby('region')['importe'].agg(['sum', 'mean', 'median', 'count'])

           sum         mean  median  count
region
Centro  705695  2594.466912  1580.0    272
Este    549745  3054.138889  1740.0    180
Norte   862360  2827.409836  1400.0    305
Oeste   626295  3085.197044  1820.0    203
Sur     699920  2916.333333  1340.0    240

In [9]:
# varias estadisticas
# le adicionamos un alias
ventas_df.groupby('region')['importe'].agg(
    importe_total = 'sum',
    importe_promedio = 'mean',
    importe_medinana = 'median',
    cantidad_registros = 'count'
)

        importe_total  importe_promedio  importe_medinana  cantidad_registros
region
Centro         705695       2594.466912            1580.0                 272
Este           549745       3054.138889            1740.0                 180
Norte          862360       2827.409836            1400.0                 305
Oeste          626295       3085.197044            1820.0                 203
Sur            699920       2916.333333            1340.0                 240

### AGRUPAR X N-REGISTROS

In [10]:
ventas_df.groupby(['region', 'categoria'])['importe'].agg(
    importe_total = 'sum',
    importe_promedio = 'mean',
    importe_medinana = 'median'
)

                   importe_total  importe_promedio  importe_medinana
region categoria
Centro Accesorios          56895        605.265957             495.0
       Mobiliario         201520       2651.578947            2250.0
       Tecnologia         447280       4385.098039            3200.0
Este   Accesorios          44585        675.530303             555.0
       Mobiliario         136520       2730.400000            2700.0
       Tecnologia         368640       5760.000000            4160.0
Norte  Accesorios          78630        639.268293             520.0
       Mobiliario         200130       2668.400000            2250.0
       Tecnologia         583600       5454.205607            3840.0
Oeste  Accesorios          40205        628.203125             497.5
       Mobiliario         156170       2692.586207            2800.0
       Tecnologia         429920       5307.654321            3840.0
Sur    Accesorios          57800        642.222222             530.0
       Mobiliario         155320       2724.912281            2800.0
       Tecnologia         486800       5234.408602            3840.0

In [14]:
# estadisticas de varias columnas

ventas_df.groupby('region').agg({
    'importe': ['sum', 'mean', 'max'],
    'unidades': ['sum'],
    'producto': ['nunique']
})

       importe                     unidades producto
           sum         mean    max      sum  nunique
region
Centro  705695  2594.466912  15600     1933        8
Este    549745  3054.138889  16800     1384        8
Norte   862360  2827.409836  16800     2166        8
Oeste   626295  3085.197044  15600     1469        8
Sur     699920  2916.333333  16800     1779        8

In [15]:

ventas_df.groupby(['region', 'categoria']).agg({
    'importe': ['sum', 'mean', 'max'],
    'unidades': ['sum'],
    'producto': ['nunique']
})

                  importe                     unidades producto
                      sum         mean    max      sum  nunique
region categoria
Centro Accesorios   56895   605.265957   1820      646        3
       Mobiliario  201520  2651.578947   6300      574        2
       Tecnologia  447280  4385.098039  15600      713        3
Este   Accesorios   44585   675.530303   1820      484        3
       Mobiliario  136520  2730.400000   6300      388        2
       Tecnologia  368640  5760.000000  16800      512        3
Norte  Accesorios   78630   639.268293   1820      862        3
       Mobiliario  200130  2668.400000   6300      566        2
       Tecnologia  583600  5454.205607  16800      738        3
Oeste  Accesorios   40205   628.203125   1820      453        3
       Mobiliario  156170  2692.586207   6300      443        2
       Tecnologia  429920  5307.654321  15600      573        3
Sur    Accesorios   57800   642.222222   1690      649        3
       Mobiliario  155320  2724.912281   6300      426        2
       Tecnologia  486800  5234.408602  16800      704        3

In [16]:
ventas_df.groupby(['region', 'categoria', 'vendedor']).agg({
    'importe': ['sum', 'mean', 'max'],
    'unidades': ['sum'],
    'producto': ['nunique']
})

                              importe                     unidades producto
                                  sum         mean    max      sum  nunique
region categoria  vendedor
Centro Accesorios Ana Torres     4100   341.666667    910       76        2
                  Carlos Vega    5150   468.181818   1560       68        3
                  Elena Mora     7035   703.500000   1820       87        3
                  Javier Sanz    7500   681.818182   1820       68        3
                  Luis Gomez     5205   578.333333   1235       71        3
...                               ...          ...    ...      ...      ...
Sur    Tecnologia Javier Sanz   62000  5166.666667  13200       94        3
                  Luis Gomez    73760  8195.555556  16800      101        3
                  Marta Ruiz    24400  3050.000000   8400       50        3
                  Pedro Diaz    24640  3080.000000   7680       49        2
                  Sofia Leon    96720  6448.000000  16800      123        3

[120 rows x 5 columns]