### CONCATENADO DE TABLAS

In [46]:
import pandas as pd

enero = pd.DataFrame({
    'mes': ['Enero'],
    'numero_mes': [1]
})

febrero = pd.DataFrame({
    'mes': ['febrero'],
    'numero_mes': [2]
})

marzo = pd.DataFrame({
    'mes': ['marzo'],
    'numero_mes': [3]
})

print(enero)
print(febrero)
print(marzo)

     mes  numero_mes
0  Enero           1
       mes  numero_mes
0  febrero           2
     mes  numero_mes
0  marzo           3

In [47]:
# unir tablas sin criterio, copiar una tras otra
# concatenando por columnas
pd.concat(
    [enero, febrero, marzo],
    axis=1 # concatenar x el eje 1 (eje de las columnas)
)

     mes  numero_mes      mes  numero_mes    mes  numero_mes
0  Enero           1  febrero           2  marzo           3

In [48]:
# unir tablas sin criterio, copiar una tras otra
# concatenando por filas
pd.concat(
    [enero, febrero, marzo],
    axis=0 # concatenar x el eje 0 (eje de las filas)
)

       mes  numero_mes
0    Enero           1
0  febrero           2
0    marzo           3

In [49]:
# unir tablas sin criterio, copiar una tras otra
# concatenando por filas y resetear indice
pd.concat(
    [enero, febrero, marzo],
    axis=0 # concatenar x el eje 0 (eje de las filas)
).reset_index(drop=True) #si no tiene drop=True, te trae el indice como columna

       mes  numero_mes
0    Enero           1
1  febrero           2
2    marzo           3

In [50]:
# unir tablas sin criterio, copiar una tras otra
# concatenando por filas y resetear indice, traendo el indice como columna
pd.concat(
    [enero, febrero, marzo],
    axis=0 # concatenar x el eje 0 (eje de las filas)
).reset_index()

   index      mes  numero_mes
0      0    Enero           1
1      0  febrero           2
2      0    marzo           3

### JOIN

In [51]:
import pandas as pd
ventas_df = pd.read_csv("../data/ventas.csv")
catalogo_productos_df = pd.read_csv("../data/catalogo_productos.csv")

In [52]:
ventas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 128.0 KB

In [53]:
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [54]:
catalogo_productos_df.head(10)

      producto  coste_unitario proveedor  stock
0   Laptop Pro             780  TecnoSur     45
1   Monitor 27             195  TecnoSur    120
2  Teclado Mec              52   InputCo    300
3   Raton Ergo              21   InputCo    500
4   Silla Ergo             160   ErgoLab     80
5   Escritorio             250   ErgoLab     35
6  Auriculares              68   InputCo    210
7   Tablet Air             390  TecnoSur     60

In [55]:
catalogo_productos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   producto        8 non-null      str
 1   coste_unitario  8 non-null      int64
 2   proveedor       8 non-null      str
 3   stock           8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 529.0 bytes

### LEFT JOIN

In [56]:
left_join = ventas_df.merge(catalogo_productos_df, on='producto', how='left')
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00,21,InputCo,500

In [57]:
ventas_df.loc[1199, 'producto'] = 'Monitor 32'
ventas_df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.00

In [58]:
left_join = ventas_df.merge(catalogo_productos_df, on='producto', how='left')
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68.0,InputCo,210.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195.0,TecnoSur,120.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160.0,ErgoLab,80.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780.0,TecnoSur,45.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68.0,InputCo,210.0
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21.0,InputCo,500.0
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780.0,TecnoSur,45.0
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195.0,TecnoSur,120.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195.0,TecnoSur,120.0
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.00,NaN,NaN,NaN

### INNER JOIN

In [59]:
inner_join_df = ventas_df.merge(catalogo_productos_df, on='producto', how='inner')
inner_join_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00,390,TecnoSur,60
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120

### RIGHT JOIN

In [60]:
left_join = ventas_df.merge(catalogo_productos_df, on='producto', how='right')
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0,780,TecnoSur,45
1,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1,780,TecnoSur,45
2,2024-01-06,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,8,1200,0.0,780,TecnoSur,45
3,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.0,780,TecnoSur,45
4,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.0,780,TecnoSur,45
...,...,...,...,...,...,...,...,...,...,...,...
1194,2024-12-19,Oeste,Marta Ruiz,Tablet Air,Tecnologia,8,640,0.0,390,TecnoSur,60
1195,2024-12-24,Este,Elena Mora,Tablet Air,Tecnologia,5,640,0.0,390,TecnoSur,60
1196,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.0,390,TecnoSur,60
1197,2024-12-28,Este,Luis Gomez,Tablet Air,Tecnologia,13,640,0.0,390,TecnoSur,60
1198,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.0,390,TecnoSur,60

In [61]:
import pandas as pd
producto_adicional = pd.DataFrame(
    {
        'producto': ['iPhone 18 Pro Max'],
        'coste_unitario': [1000],
        'proveedor': ['Apple'],
        'stock': [250]
    }
)

producto_adicional.info()

pd.concat([catalogo_productos_df, producto_adicional ], axis=0)
catalogo_productos_df.tail()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   producto        1 non-null      str
 1   coste_unitario  1 non-null      int64
 2   proveedor       1 non-null      str
 3   stock           1 non-null      int64
dtypes: int64(2), str(2)
memory usage: 186.0 bytes

      producto  coste_unitario proveedor  stock
3   Raton Ergo              21   InputCo    500
4   Silla Ergo             160   ErgoLab     80
5   Escritorio             250   ErgoLab     35
6  Auriculares              68   InputCo    210
7   Tablet Air             390  TecnoSur     60

### LEFT ANTI JOIN

In [62]:
left_anti_join = ventas_df.merge(catalogo_productos_df, on='producto', how='left_anti')
left_anti_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.0,NaN,NaN,NaN

### RIGTH ANTI JOIN

In [63]:
rigth_anti_join = ventas_df.merge(catalogo_productos_df, on='producto', how='right_anti')
rigth_anti_join

Empty DataFrame
Columns: [fecha, region, vendedor, producto, categoria, unidades, precio_unitario, descuento, coste_unitario, proveedor, stock]
Index: []

### CROSS JOIN

In [64]:
cross_join = catalogo_productos_df.merge(catalogo_productos_df, how='cross')
cross_join

,producto_x,coste_unitario_x,proveedor_x,stock_x,producto_y,coste_unitario_y,proveedor_y,stock_y
0,Laptop Pro,780,TecnoSur,45,Laptop Pro,780,TecnoSur,45
1,Laptop Pro,780,TecnoSur,45,Monitor 27,195,TecnoSur,120
2,Laptop Pro,780,TecnoSur,45,Teclado Mec,52,InputCo,300
3,Laptop Pro,780,TecnoSur,45,Raton Ergo,21,InputCo,500
4,Laptop Pro,780,TecnoSur,45,Silla Ergo,160,ErgoLab,80
...,...,...,...,...,...,...,...,...
59,Tablet Air,390,TecnoSur,60,Raton Ergo,21,InputCo,500
60,Tablet Air,390,TecnoSur,60,Silla Ergo,160,ErgoLab,80
61,Tablet Air,390,TecnoSur,60,Escritorio,250,ErgoLab,35
62,Tablet Air,390,TecnoSur,60,Auriculares,68,InputCo,210
63,Tablet Air,390,TecnoSur,60,Tablet Air,390,TecnoSur,60